name: "My Action"
description: "Evaluacion 1 - Backend"
author: "amezaf@uninorte.edu.co"

inputs:
  N_INDEX:
    description: "N viene siendo la posicion en la serie fibbonacci"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
