name: A workflow for my Fibonacci action
on: push


jobs:
  build:
    name: Run the Fibonacci action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./parcial_1
        with:
          N_INDEX: 9

